version: 2

sources: 
  - name: raw 
    schema: gz_raw_data
    tables: 
      - name: sales 
        freshness: 
          warn_after: {count: 90, period: day}
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"    
        identifier: raw_gz_sales
        description: sales of Greenweez / we have one row per productid found in each orders_id
        columns:
          - name: date_date
            description: the date of purchase
          - name: orders_id
            description: foreign key to ship
          - name: pdt_id
            description: foreign key to product
          - name: revenue
            description: the amount paid by the customer to purcahse the product. revenue = quantity * selling_price
          - name: quantity
            description: the quantity of products purchased for this order
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
      - name: product
        identifier: raw_gz_product
        description: products of greenweez
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
              - not_null 
          - name: purchase_price
            description: the purchase price of the product
      - name: ship
        identifier: raw_gz_ship
        description: ship of greenweez
        columns:
          - name: orders_id
            description: primary key of the table
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: the price the customer pays for shipping
          - name: log_cost
            description: the cost of preparing the parcel in the warehouse
          - name: ship_cost
            description: the shipping cost paid by freenweez to the carrier/transporter
